// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "This API is for checking server health. The api return server name, version and revision.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Get server health information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResponse"
                        }
                    }
                }
            }
        },
        "/os/android": {
            "get": {
                "description": "This API is for getting android information.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "os"
                ],
                "summary": "Get android information",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.OSResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthResponse": {
            "type": "object",
            "properties": {
                "name": {
                    "description": "@Description\tName is server name.",
                    "type": "string"
                },
                "revision": {
                    "description": "@Description\tRevision is git revision",
                    "type": "string"
                },
                "version": {
                    "description": "@Description\tVersion is repository tag version",
                    "type": "string"
                }
            }
        },
        "api.OSResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "description": "@Description\tItems is os information list.",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.OS"
                    }
                }
            }
        },
        "model.OS": {
            "type": "object",
            "properties": {
                "api_level": {
                    "description": "APILevel is os APILevel.",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                },
                "code_name": {
                    "description": "CodeName is os CodeName.",
                    "type": "string"
                },
                "name": {
                    "description": "Name is os Name.",
                    "type": "string"
                },
                "release": {
                    "description": "Release is os Release.",
                    "type": "string"
                },
                "version": {
                    "description": "Version is os Version.",
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
